### ISSUE TITLE
When will the Gem be published?

### ISSUE THREAD

**Issue by ktanaka101** [Hummingbird-RegTech/rspec-inline-snapshot#1]
Hi!
Thanks for the great Gem. I am glad because I was in the process of creating a similar Gem.

When will the Gem be published on [rubygems.org](https://rubygems.org/search?query=rspec+snapshot)?
I have tried using the Gem, and it appears to work well.
I can't wait to be able to run `gem install rspec-inline-snapshot`.

**Comment by simoleone** [comment]
Hey! We're so glad you found it right after we published it to Github 😄 , we just hadn't got a chance to publish to rubygems.org yet. I just pushed it now, so it should be available 🎉  https://rubygems.org/gems/rspec-inline-snapshot

Hope you continue to find it useful!

**Comment by ktanaka101** [comment]
Thank you for your swift response!
